-- SUM
-- MAX
-- MIN
-- AVG
-- COUNT

SELECT ESTADO, BAIRRO, SUM(LIMITE_DE_CREDITO) FROM TABELA_DE_CLIENTES GROUP BY ESTADO, BAIRRO ORDER BY ESTADO;

SELECT ESTADO, CAST(AVG(LIMITE_DE_CREDITO) AS INT) AS LIMITE_DE_CREDITO FROM TABELA_DE_CLIENTES GROUP BY ESTADO;

SELECT * FROM TABELA_DE_VENDEDORES;

SELECT ESTADO, MAX(LIMITE_DE_CREDITO) AS LIMITE_DE_CREDITO FROM TABELA_DE_CLIENTES GROUP BY ESTADO;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT * FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035';

SELECT COUNT(*) AS QUANTIDADE_TOTAL FROM ITENS_NOTAS_FISCAIS 
WHERE CODIGO_DO_PRODUTO = '1101035'
AND QUANTIDADE = 99;

SELECT EMBALAGEM, COUNT(*) AS "QUANTIDADE TOTAL" FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT * FROM TABELA_DE_CLIENTES;

