-- Aplicação do case

-- Colocamos uma condicional e a partir de um determinado valor apresentamos um resultado

SELECT CODIGO_DO_PRODUTO, QUANTIDADE, PRECO,
    (CASE WHEN PRECO <= 10 THEN 'PREÇO BAIXO'
    WHEN PRECO > 10 AND PRECO <= 20 THEN 'PREÇO MÉDIO'
    WHEN PRECO > 20 AND PRECO <= 30 THEN 'PREÇO ALTO'
    ELSE 'PREÇO IMPRATICAVEL'
    END) AS STATUS_PRECO
FROM ITENS_NOTAS_FISCAIS ORDER BY PRECO ASC;

SELECT CODIGO_DO_PRODUTO, PRECO, QUANTIDADE,
    (CASE WHEN PRECO <= 10 THEN 'PREÇO BAIXO'
    WHEN PRECO > 10 AND PRECO <= 20 THEN 'PREÇO MÉDIO'
    WHEN PRECO > 20 AND PRECO <= 30 THEN 'PREÇO ALTO'
    ELSE 'PREÇO IMPRATICAVEL'
    END) AS STATUS_PRECO
FROM ITENS_NOTAS_FISCAIS ORDER BY PRECO ASC;

SELECT DISTINCT CODIGO_DO_PRODUTO FROM ITENS_NOTAS_FISCAIS ORDER BY CODIGO_DO_PRODUTO ASC;

SELECT * FROM ITENS_NOTAS_FISCAIS;

SELECT 
    (CASE WHEN TO_CHAR(DATA_DE_NASCIMENTO, 'YYYY') <= 1990 THEN 'IDOSO'
    WHEN TO_CHAR(DATA_DE_NASCIMENTO, 'YYYY') >= 1990 AND TO_CHAR(DATA_DE_NASCIMENTO, 'YYYY') <= 1995  THEN 'JOVÉM'
    WHEN TO_CHAR(DATA_DE_NASCIMENTO, 'YYYY') > 1995 THEN 'CRIANÇA'
    END) AS CLASSIFICACAO_IDADE
FROM TABELA_DE_CLIENTES;