SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' OR TAMANHO = '470 ml';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' AND TAMANHO = '470 ml';
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'Manga' AND TAMANHO = '470 ml');
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN ('Laranja', 'Manga');
SELECT * FROM TABELA_DE_CLIENTES;
SELECT * FROM TABELA_DE_CLIENTES WHERE NOT CIDADE = 'Sao Paulo' AND IDADE >= 18;