SELECT * FROM TABELA_DE_VENDEDORES;

-- Exibir VARCHAR em minusculo
SELECT LOWER(NOME) AS NOME FROM TABELA_DE_VENDEDORES WHERE ROWNUM <= 2;

-- Exibir VARCHAR em maiusculo
SELECT UPPER(NOME) AS NOME FROM TABELA_DE_VENDEDORES;

-- Acrescentar em todo inicio de palavra uma letra maiuscula
SELECT * FROM TABELA_DE_PRODUTOS;
SELECT INITCAP(NOME_DO_PRODUTO) FROM TABELA_DE_PRODUTOS;

-- Concatenar duas Strings
SELECT * FROM TABELA_DE_CLIENTES;
SELECT CONCAT(ENDERECO_1,BAIRRO) FROM TABELA_DE_CLIENTES;

-- Alteranativa para concatenação utilizando PIPE ( | )
SELECT NOME, 'Endereço: ' || ENDERECO_1 || '. Bairro: ' || BAIRRO || ', ' || CIDADE || '/' || ESTADO ENDERECO
FROM TABELA_DE_CLIENTES;

-- Dimensionar para direita/esquerda o texto
SELECT LPAD(NOME_DO_PRODUTO, 60) FROM TABELA_DE_PRODUTOS;
SELECT LPAD(' |' || NOME_DO_PRODUTO || '| ', 60, '_') AS NOME_DO_PRODUTO FROM TABELA_DE_PRODUTOS;

SELECT RPAD(NOME_DO_PRODUTO, 60) FROM TABELA_DE_PRODUTOS;
SELECT RPAD(' |' || NOME_DO_PRODUTO || '| ', 60, '_') AS NOME_DO_PRODUTO FROM TABELA_DE_PRODUTOS;

-- Pegar uma quantidade especifica de caracter a partir do indice
SELECT NOME_DO_PRODUTO, SUBSTR(NOME_DO_PRODUTO, 2, 4) AS NOME_MODIFICADO
FROM TABELA_DE_PRODUTOS;

-- Pega a quantidade númerica especifica de caracter antes do valor informado
SELECT NOME_DO_PRODUTO, INSTR(NOME_DO_PRODUTO, '-') AS QUANTIDADE FROM TABELA_DE_PRODUTOS;

-- Apagar espeços do lado direito/esquerdo do texto
SELECT LTRIM('               AGORA VAI') AS TEXTO FROM DUAL;
SELECT RTRIM('AGORA VAI               ') AS TEXTO FROM DUAL;
SELECT LENGTH(RTRIM('AGORA VAI               ')) AS TAMANHO FROM DUAL;

-- Substituir valores com replace
SELECT NOME_DO_PRODUTO, REPLACE(INITCAP(NOME_DO_PRODUTO), 'Ml', 'ML') AS "NOME DO PRODUTO"
FROM TABELA_DE_PRODUTOS;