SELECT SYSDATE FROM DUAL;

-- Apresentação do ano atual e hora
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MM:SS') AS DIA_ATUAL FROM DUAL;

-- Operações Matemáticas com data
SELECT SYSDATE + 10 AS DIA_ATUAL_MAIS_DEZ FROM DUAL;
SELECT SYSDATE - 10 AS DIA_ATUAL_MENOS_DEZ FROM DUAL;

-- Diferença entre datas
SELECT MONTHS_BETWEEN(SYSDATE, TO_DATE('2022-07-15','YYYY-MM-DD')) FROM DUAL;

-- Adição de mês para uma data específica
SELECT ADD_MONTHS(SYSDATE, 3) FROM DUAL;

-- Verificar o proximo dia 
-- SEGUNDA, TERÇA, QUARTA, QUINTA, SEXTA, SÁBADO E DOMINGO
SELECT NEXT_DAY(SYSDATE, 'TERÇA') FROM DUAL;

-- Último dia do ano
SELECT LAST_DAY(SYSDATE) FROM DUAL;

-- Truncar para a partir de uma data
-- YEAR, MONTH E DAY
SELECT TRUNC(SYSDATE, 'YEAR') FROM DUAL;
SELECT TRUNC(SYSDATE, 'MONTH') FROM DUAL;
SELECT TRUNC(SYSDATE, 'DAY') FROM DUAL;

-- ROUND geralmente arredonda para cima
-- YEAR, MONTH E DAY
SELECT ROUND(SYSDATE, 'YEAR') FROM DUAL;
SELECT ROUND(SYSDATE, 'MONTH') FROM DUAL;
SELECT ROUND(SYSDATE, 'DAY') FROM DUAL;

SELECT * FROM TABELA_DE_CLIENTES;

DESC TABELA_DE_CLIENTES;

SELECT NOME, TRUNC(MONTHS_BETWEEN(SYSDATE, DATA_DE_NASCIMENTO)/12) || ' anos' AS IDADE
FROM TABELA_DE_CLIENTES;