SELECT * FROM TABELA_DE_VENDEDORES;

SELECT TO_DATE('12/11/2021', 'DD/MM/YYYY') AS DATA FROM DUAL;

SELECT REPLACE(T.DATA, '-', ' ') AS DATA 
FROM (SELECT REPLACE(TO_CHAR(SYSDATE, 'DD/Month/YY-HH24:MM:SS'), ' ', '') AS DATA FROM DUAL) T;

-- OBTER O ANO/MÊS/DAY A PARTIR DE UMA DATA
SELECT EXTRACT (MONTH FROM TO_DATE('12/11/2022', 'MM/DD/YYYY')) AS MES FROM DUAL;
SELECT EXTRACT (YEAR FROM TO_DATE('12/11/2022', 'MM/DD/YYYY')) AS MES FROM DUAL;
SELECT EXTRACT (DAY FROM TO_DATE('12/11/2022', 'MM/DD/YYYY')) AS MES FROM DUAL;

-- VARCHAR PARA NUMBER
SELECT TO_NUMBER('3050') FROM DUAL;
SELECT TO_NUMBER('3050') + 200 FROM DUAL;

-- Substitui valores caso o campo seja NULL
SELECT NOME, ENDERECO_1, NVL(ENDERECO_2, 'Campo vazio') AS ENDERECO_2 FROM TABELA_DE_CLIENTES;

-- Obtém o maior valor entre os campos citados
SELECT GREATEST(1, 4, 5) FROM DUAL;

SELECT * FROM TABELA_DE_CLIENTES;
SELECT CPF FROM NOTAS_FISCAIS GROUP BY CPF;
SELECT * FROM NOTAS_FISCAIS;
DESC NOTAS_FISCAIS;
SELECT * FROM ITENS_NOTAS_FISCAIS;


SELECT C.NOME, TRUNC(SUM(I.PRECO)) AS VENDA_TOTAL, TO_CHAR(N.DATA_VENDA, 'YYYY') AS ANO
FROM TABELA_DE_CLIENTES C
INNER JOIN NOTAS_FISCAIS N
ON C.CPF = N.CPF
INNER JOIN ITENS_NOTAS_FISCAIS I
ON N.NUMERO = I.NUMERO
WHERE TO_CHAR(N.DATA_VENDA, 'YYYY') = '2016'
GROUP BY TO_CHAR(N.DATA_VENDA, 'YYYY'), C.NOME;