-- HAVING é o filtro utilizado por agregação - Group By

SELECT * FROM TABELA_DE_CLIENTES;

SELECT CIDADE, ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL
FROM TABELA_DE_CLIENTES
GROUP BY CIDADE, ESTADO;

SELECT CIDADE, ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL
FROM TABELA_DE_CLIENTES
GROUP BY CIDADE, ESTADO
HAVING SUM(LIMITE_DE_CREDITO) > 810000;

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT EMBALAGEM, MIN(PRECO_DE_LISTA) AS MENOR_PRECO, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM
HAVING MIN(PRECO_DE_LISTA) >= 2 OR MAX(PRECO_DE_LISTA) <= 5;

SELECT * FROM NOTAS_FISCAIS;

SELECT CPF, COUNT(*) FROM NOTAS_FISCAIS
WHERE TO_CHAR(DATA_VENDA, 'YYYY') = 2016
GROUP BY CPF
HAVING COUNT(*) > 2000;

SELECT CPF FROM NOTAS_FISCAIS
WHERE CPF =  3623344710;