SELECT * FROM TABELA_DE_VENDEDORES;
SELECT * FROM NOTAS_FISCAIS;

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT MATRICULA, COUNT(*) AS NUMEROS_NOTAS FROM NOTAS_FISCAIS
GROUP BY MATRICULA;

SELECT A.MATRICULA, B.NOME, COUNT(*) AS NUMEROS_NOTAS FROM NOTAS_FISCAIS A
INNER JOIN TABELA_DE_VENDEDORES B
ON A.MATRICULA = B.MATRICULA
GROUP BY A.MATRICULA, B.NOME;

SELECT * FROM ITENS_NOTAS_FISCAIS;


SELECT TO_CHAR(DATA_VENDA, 'YYYY') AS DATA_VENDA, CAST(SUM(QUANTIDADE*PRECO) AS INT) AS VENDA_TOTAL_ANO 
FROM NOTAS_FISCAIS A
INNER JOIN ITENS_NOTAS_FISCAIS B
ON A.NUMERO = B.NUMERO
GROUP BY TO_CHAR(DATA_VENDA, 'YYYY')
ORDER BY DATA_VENDA;
