SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

SELECT * FROM TABELA_DE_VENDEDORES WHERE BAIRRO IN (SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES);

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT EMBALAGEM, CAST(SUM(PRECO_DE_LISTA) AS INT) AS PRECO_TOTAL
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM
HAVING SUM(PRECO_DE_LISTA) > 20;

SELECT T.EMBALAGEM, T.PRECO_TOTAL
FROM (SELECT EMBALAGEM, CAST(SUM(PRECO_DE_LISTA) AS INT) AS PRECO_TOTAL
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM) T;

SELECT CONCAT('PRODUTO: ', T.EMBALAGEM) AS EMBALAGEM, T.PRECO_TOTAL
FROM (SELECT EMBALAGEM, CAST(SUM(PRECO_DE_LISTA) AS INT) AS PRECO_TOTAL
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM) T;

SELECT * FROM NOTAS_FISCAIS;

SELECT CPF, COUNT(*) AS QUANTIDADE_NOTAS
FROM NOTAS_FISCAIS
WHERE TO_CHAR(DATA_VENDA, 'YYYY') = '2016'
GROUP BY CPF
HAVING COUNT(*) > 2000;

SELECT N.CPF, N.QUANTIDADE_NOTAS
FROM (SELECT CPF, COUNT(*) AS QUANTIDADE_NOTAS FROM NOTAS_FISCAIS  WHERE TO_CHAR(DATA_VENDA, 'YYYY') = '2016' GROUP BY CPF) N
WHERE QUANTIDADE_NOTAS > 2000;