SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

SELECT * FROM TABELA_DE_VENDEDORES WHERE BAIRRO IN (SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES);

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT EMBALAGEM, CAST(SUM(PRECO_DE_LISTA) AS INT) AS PRECO_TOTAL
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM
HAVING SUM(PRECO_DE_LISTA) > 20;

SELECT T.EMBALAGEM, T.PRECO_TOTAL
FROM (SELECT EMBALAGEM, CAST(SUM(PRECO_DE_LISTA) AS INT) AS PRECO_TOTAL
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM) T;

SELECT CONCAT('PRODUTO: ', T.EMBALAGEM) AS EMBALAGEM, T.PRECO_TOTAL
FROM (SELECT EMBALAGEM, CAST(SUM(PRECO_DE_LISTA) AS INT) AS PRECO_TOTAL
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM) T;