-- UTILIZANDO UNION PARA JUNÇÃO DE CAMPOS

-- DIFERENÇA ENTRE UNION E UNION ALL. O UNION POSSUI DISTINCT.

SELECT BAIRRO FROM TABELA_DE_CLIENTES
UNION
SELECT BAIRRO FROM TABELA_DE_VENDEDORES;

SELECT BAIRRO FROM TABELA_DE_CLIENTES
UNION ALL
SELECT BAIRRO FROM TABELA_DE_VENDEDORES;