SELECT CPF, COUNT(*) AS QUANTIDADE_NOTAS
FROM NOTAS_FISCAIS
WHERE TO_CHAR(DATA_VENDA, 'YYYY') = '2016'
GROUP BY CPF;

CREATE VIEW VENDA_ANO_2016 AS
    SELECT CPF, COUNT(*) AS QUANTIDADES_NOTAS
    FROM NOTAS_FISCAIS
    WHERE TO_CHAR(DATA_VENDA, 'YYYY') = '2016'
    GROUP BY CPF;
    
SELECT * FROM TABELA_DE_CLIENTES;

-- ANIVERSARIANTE DO MES
SELECT CPF, NOME, TO_CHAR(DATA_DE_NASCIMENTO, 'DD/MM') AS DATA_DE_NASCIMENTO
FROM TABELA_DE_CLIENTES
WHERE TO_CHAR(DATA_DE_NASCIMENTO, 'MM') = TO_CHAR(SYSDATE, 'MM');

CREATE VIEW ANIVERSARIANTE_DO_MES AS
    SELECT CPF, NOME, TO_CHAR(DATA_DE_NASCIMENTO, 'DD/MM') AS DATA_DE_NASCIMENTO
    FROM TABELA_DE_CLIENTES
    WHERE TO_CHAR(DATA_DE_NASCIMENTO, 'MM') = TO_CHAR(SYSDATE, 'MM');

SELECT * FROM ANIVERSARIANTE_DO_MES;    
SELECT * FROM VENDA_ANO_2016;

