SELECT * FROM TB_CLIENTES;
SELECT * FROM TB_PRODUTOS;
SELECT * FROM TABELA_DE_VENDEDORES;

SELECT * FROM TB_CLIENTES
WHERE DATA_NASCIMENTO = TO_DATE('30/05/22', 'DD/MM/YY');

SELECT TO_CHAR(DATA_NASCIMENTO, 'DD/Month/yyyy') FROM TB_CLIENTES;

SELECT REPLACE(TO_CHAR(DATA_NASCIMENTO, 'Day'), ' ', '') AS DATA_NASCIMENTO FROM TB_CLIENTES;

SELECT * FROM TB_CLIENTES
WHERE TO_CHAR(DATA_NASCIMENTO, 'MM') = 05;

SELECT * FROM TABELA_DE_VENDEDORES
WHERE PERCENTUAL_COMISSAO >= 10;

SELECT * FROM TABELA_DE_VENDEDORES
WHERE TO_CHAR(DATA_ADMISSAO, 'YY') <= 21 
AND DE_FERIAS = 0;


SELECT * FROM TB_PRODUTOS
WHERE PRECO_LISTA > 4; -- Maior que

SELECT * FROM TB_PRODUTOS
WHERE PRECO_LISTA < 4; -- Menor que

SELECT * FROM TB_PRODUTOS
WHERE PRECO_LISTA <> 4; -- Diferente de

SELECT * FROM TB_PRODUTOS
WHERE PRECO_LISTA >= 4; -- Maior ou igual

