INSERT INTO TB_PRODUTOS 
(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES
('1040107', 'Light - 350ML - Melancia', 'Lata', '350ML', 'Melancia', 4.56);

INSERT INTO TB_PRODUTOS 
(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES
('1037797', 'Clean - 2 LITROS - Laranja', 'PET', '2 LITROS', 'Laranja', 16.01);

INSERT INTO TB_PRODUTOS 
(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES
('1000889', 'Sabor da Montanha - 700ML - Uva', 'Garrafa', '700ML', 'Uva', 6.31);

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00233', 'JOSÉ GERALDO DA FONSECA', 10.0);

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00235', 'Márcio Almeida Silva', 8.0);

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00236', 'Cláudia Morais', 8.0);

SELECT * FROM TB_PRODUTOS;
SELECT * FROM TB_CLIENTES;

INSERT INTO TB_CLIENTES 
(CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, ESTADO, CEP, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA)
VALUES ('23206904895', 'Jéssiva Vinte', 'Rua Direita', '192', 'Centro', 'SP', '03821450', 28, 'F', 2500.00, 1000.00, 1);

SELECT * FROM TABELA_DE_VENDEDORES;