ALTER TABLE TB_PRODUTOS ADD CONSTRAINT PK_TB_PRODUTOS 
PRIMARY KEY (PRODUTO);

ALTER TABLE TB_CLIENTES ADD CONSTRAINT PK_TB_CLIENTES
PRIMARY KEY (CPF);

ALTER TABLE TB_CLIENTES ADD DATA_NASCIMENTO DATE;

UPDATE TB_CLIENTES SET DATA_NASCIMENTO = TO_DATE('30/05/2022', 'DD/MM/YYYY');

DESCRIBE TB_PRODUTOS;
DESC TB_CLIENTES;

SELECT DATA_NASCIMENTO FROM TB_CLIENTES;

SELECT * FROM TABELA_DE_VENDEDORES;

DESC TABELA_DE_VENDEDORES;

ALTER TABLE TABELA_DE_VENDEDORES ADD DATA_DMISSAO DATE;
ALTER TABLE TABELA_DE_VENDEDORES RENAME COLUMN DATA_DMISSAO TO DATA_ADMISSAO; 
ALTER TABLE TABELA_DE_VENDEDORES ADD DE_FERIAS NUMBER(1);

UPDATE TABELA_DE_VENDEDORES 
SET DATA_ADMISSAO = TO_DATE('15/03/2021', 'DD/MM/YYYY')
WHERE MATRICULA = '00233';

UPDATE TABELA_DE_VENDEDORES 
SET DATA_ADMISSAO = TO_DATE('15/03/2021', 'DD/MM/YYYY')
WHERE MATRICULA = '00235';

UPDATE TABELA_DE_VENDEDORES 
SET DATA_ADMISSAO = TO_DATE('15/03/2021', 'DD/MM/YYYY')
WHERE MATRICULA = '00236';

UPDATE TABELA_DE_VENDEDORES SET DE_FERIAS = 0;