EXECUTE user_dev.CLIENTE_PAC.INCLUIR_CLIENTE(10, 'PRIMEIRO CLIENTE USANDO PACKAGE', '45678', 2, 120000);
COMMIT;
SELECT * FROM user_dev.cliente;

CREATE PUBLIC SYNONYM CLIENTE FOR USER_DEV.CLIENTE;
CREATE PUBLIC SYNONYM CLIENTE_PAC FOR USER_DEV.CLIENTE_PAC;
COMMIT;
