SELECT * FROM PRODUTOS;

-- Replicar uma tabela
CREATE TABLE PRODUTO2 AS (SELECT * FROM PRODUTOS);

-- Inserir novos dados
INSERT INTO PRODUTO2 (SELECT * FROM PRODUTOS);

SELECT COUNT(*) FROM PRODUTO2;

SELECT * FROM PRODUTO2;

-- UPDATE todos os dados
UPDATE PRODUTO2 SET PRECO_LISTA = 8;

-- UPDATE todos os campos de acordo com a tabela PRODUTOS
UPDATE PRODUTO2 P SET PRECO_LISTA = (SELECT PRECO_LISTA FROM PRODUTOS PL WHERE PL.CODIGO = P.CODIGO)
WHERE EXISTS (SELECT PRECO_LISTA FROM PRODUTOS L WHERE L.CODIGO = P.CODIGO);

SELECT L.CODIGO, L.PRECO_LISTA, T.PRECO_LISTA FROM PRODUTOS L
INNER JOIN PRODUTO2 T
ON L.CODIGO = T.CODIGO;


-- Para efetivar uma "transação" é necessário colocar um commit;
COMMIT;

-- Para desfazer uma "transação" é necessário colocar um rollback;
ROLLBACK;