DESC PRODUTOS;

INSERT INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES ('1040107', 'Light - 350ML - Melancia', 'Melancia', '350ML', 'Lata', 4.56);

SELECT * FROM PRODUTOS;

INSERT INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES ('1040108', 'Light - 350ML - Graviola', 'Graviola', '350ML', 'Lata', 4.00);

UPDATE PRODUTOS SET PRECO_LISTA = 4.99 WHERE CODIGO = '1040108';

INSERT INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES ('1040109', 'Light - 350ML - Manga', 'Manga', '350ML', 'PET', 4.22);


INSERT ALL 
INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA) VALUES ('1040110', 'Light - 350ML - Goiaba', 'Goiaba', '350ML', 'Garrafa', 3.10)
INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA) VALUES ('1040111', 'Light - 350ML - Goiaba', 'Goiaba', '350ML', 'Garrafa', 2.00)
INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA) VALUES ('1040112', 'Light - 600ML - Tangerina', 'Tangerina', '600ML', 'Garrafa', 8.50)
SELECT * FROM DUAL;

UPDATE PRODUTOS SET DESCRITOR = 'Light - 350ML - Laranja', SABOR = 'Laranja' WHERE CODIGO = '1040110';

SELECT * FROM CLIENTE;

INSERT INTO CLIENTE (CPF, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_NASCIMENTO, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA)
VALUES ('1478662710', 'Érica Carvalho', 'R. Iriquitia', 'Jardins', 'São Paulo', 'SP', '80012212', TO_DATE('01/09/1990', 'DD/MM/YYYY'), 27, 'F', 17000, 24500, 1);

DESC CLIENTE;

SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO, IDADE, SEXO, LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUME_DE_COMPRA AS VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM TABELA_DE_CLIENTES;

INSERT INTO CLIENTE (SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO, IDADE, SEXO, LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUME_DE_COMPRA AS VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM TABELA_DE_CLIENTES);

UPDATE CLIENTE SET ENDERECO = 'R. Jorge Emilio', BAIRRO = 'Santo Amaro', CIDADE = 'São Paulo', ESTADO = 'SP', CEP = '8833223'
WHERE CPF = '19290992743';

SELECT * FROM CLIENTE WHERE CPF = '19290992743';
SELECT * FROM TABELA_DE_VENDEDORES;
SELECT * FROM VENDEDORES;

INSERT INTO VENDEDORES (SELECT MATRICULA, NOME, BAIRRO, PERCENTUAL_COMISSAO AS COMISSAO, DATA_ADMISSAO, DE_FERIAS AS FERIAS FROM TABELA_DE_VENDEDORES);

UPDATE VENDEDORES SET MATRICULA = SUBSTR(MATRICULA, 3, 3);

UPDATE VENDEDORES A SET A.FERIAS = (SELECT V.DE_FERIAS FROM TABELA_DE_VENDEDORES V WHERE A.MATRICULA = SUBSTR(V.MATRICULA, 3, 3))
WHERE EXISTS (SELECT 1 FROM TABELA_DE_VENDEDORES T WHERE A.MATRICULA = SUBSTR(T.MATRICULA, 3, 3));

UPDATE VENDEDORES A SET MATRICULA = (SELECT T.MATRICULA FROM TABELA_DE_VENDEDORES T WHERE A.MATRICULA = SUBSTR(T.MATRICULA, 3, 3))
WHERE EXISTS (SELECT 1 FROM TABELA_DE_VENDEDORES T WHERE A.MATRICULA = SUBSTR(T.MATRICULA, 3, 3));


