DESC PRODUTOS;

DESC TABELA_DE_PRODUTOS;
SELECT * FROM TABELA_DE_PRODUTOS;
SELECT * FROM PRODUTOS;

SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA
FROM TABELA_DE_PRODUTOS;

-- INSERIR DADOS DE OUTRA TABELA
-- ATENTAR A ORDEM CORRETA DOS CAMPOS
-- VERIFICAR SE NÃO HÁ RESTRIÇÃO DE CHAVE PRIMARIA

INSERT INTO PRODUTOS (SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA
FROM TABELA_DE_PRODUTOS);

-- ALTERAR A TIPAGEM DO CAMPO
-- ALTER TABLE PRODUTOS MODIFY (EMBALAGEM VARCHAR(50));

-- DELETE PRODUTOS WHERE CODIGO = '1040107';

-- UPDATE PRODUTOS SET DESCRITOR = INITCAP(DESCRITOR); 