--OBTER CATEGORIA COM CONDICIONAIS

SET SERVEROUTPUT ON;

DECLARE
    v_FATURAMENTO_PREVISTO TAB_CLIENTE.FATURAMENTO_PREVISTO%TYPE := 1000000;
    v_CATEGORIA TAB_CLIENTE.CATEGORIA%TYPE;
BEGIN
    IF v_FATURAMENTO_PREVISTO < 10000 THEN
    v_CATEGORIA := 'PEQUENO';
    ELSIF v_FATURAMENTO_PREVISTO < 100000 THEN
    v_CATEGORIA := 'MÉDIO';
    ELSIF v_FATURAMENTO_PREVISTO < 1000000 THEN
    v_CATEGORIA := 'GRANDE';
    ELSE
    v_CATEGORIA := 'FATURAMENTO ACIMA DO PREVISTO';
    END IF;
    DBMS_OUTPUT.put_line('O resultado do Faturamento é: '|| v_CATEGORIA);
END;


SELECT * FROM TAB_SEGMERCADO;
DESC TAB_CLIENTE;

SELECT * FROM TAB_CLIENTE;

ALTER TABLE TAB_CLIENTE MODIFY (CATEGORIA VARCHAR(40));