ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

CREATE USER CURSOPLSQL IDENTIFIED BY CURSOPLSQL DEFAULT TABLESPACE USERS;

GRANT CONNECT, RESOURCE TO CURSOPLSQL;

-- ACESSO PARA REALIZAÇÃO DE ALTERAÇÕES NO BANCO
ALTER USER CURSOPLSQL QUOTA UNLIMITED ON USERS;

