DECLARE
    CURSOR cur_CLIENTE IS SELECT ID FROM TAB_CLIENTE;
    v_ID TAB_CLIENTE.ID%TYPE;
    v_ID_ATUALIZAR TAB_CLIENTE.ID%TYPE := 5;
BEGIN
    OPEN cur_CLIENTE;
    LOOP
        FETCH cur_CLIENTE INTO v_ID;
    EXIT WHEN cur_CLIENTE%NOTFOUND;
        ATUALIZAR_SEGMERCADO_ID(v_ID, v_ID_ATUALIZAR);
    END LOOP;
    CLOSE cur_CLIENTE;
END;

SELECT * FROM TAB_CLIENTE;
SELECT * FROM TAB_SEGMERCADO;