

CREATE OR REPLACE PROCEDURE ATUALIZAR_ID
(v_ID TAB_CLIENTE.ID%TYPE, v_ATUALIZAR_SEGMERCADO_ID TAB_CLIENTE.SEGMERCADO_ID%TYPE)
IS
BEGIN
    UPDATE TAB_CLIENTE SET SEGMERCADO_ID = v_ATUALIZAR_SEGMERCADO_ID
    WHERE ID = v_ID;
    COMMIT;
END;

EXECUTE ATUALIZAR_ID(1, 5);

SELECT * FROM TAB_SEGMERCADO;

EXEC INCLUIR_CLIENTE(2, 'LOJA VANS', '54321', 5, SYSDATE, 5000);
EXEC INCLUIR_CLIENTE(3, 'LOJA ELEMENT', '12345', 5, SYSDATE, 10000);
EXEC INCLUIR_CLIENTE(4, 'LOJA FIDO DIDO', '98765', 5, SYSDATE, 100);
EXEC INCLUIR_CLIENTE(5, 'PLAYSTATION STORE', '76543', 5, SYSDATE, 100000);

SELECT * FROM TAB_CLIENTE;