SELECT * FROM TAB_CLIENTE;

DECLARE
    v_SEGMERCADO_ID TAB_CLIENTE.SEGMERCADO_ID%TYPE := 2;
BEGIN
    FOR INDICE IN 1..6 LOOP
    ATUALIZAR_ID(v_ATUALIZAR_SEGMERCADO_ID => v_SEGMERCADO_ID, v_ID => INDICE);
    END LOOP;
END;

SELECT * FROM TAB_SEGMERCADO;

SELECT * FROM TAB_CLIENTE C
INNER JOIN TAB_SEGMERCADO S
ON C.SEGMERCADO_ID = S.ID;