DECLARE
    v_DESCRICAO TAB_SEGMERCADO.DESCRICAO%TYPE;
BEGIN
    SELECT DESCRICAO INTO v_DESCRICAO FROM TAB_SEGMERCADO WHERE ID = 1;
    dbms_output.put_line(v_DESCRICAO);
END;

--FUNÇÃO
CREATE OR REPLACE FUNCTION obter_descricao_segmercado(v_ID TAB_SEGMERCADO.ID%TYPE)
    RETURN TAB_SEGMERCADO.DESCRICAO%TYPE
IS 
    v_DESCRICAO TAB_SEGMERCADO.DESCRICAO%TYPE;
BEGIN
    SELECT DESCRICAO INTO v_DESCRICAO FROM TAB_SEGMERCADO WHERE ID = v_ID;
    RETURN v_DESCRICAO;
END;

SELECT * FROM TAB_SEGMERCADO;

-- EXECUÇÃO DA FUNÇÃO ATRAVÉS DO SQL DEVELOPER

VARIABLE g_DESCRICAO VARCHAR2(100);

EXECUTE :g_DESCRICAO:=obter_descricao_segmercado(2);

PRINT g_DESCRICAO;

-- EXECUÇÃO DA FUNÇÃO ATRAVES PL/SQL

DECLARE
    v_DESCRICAO TAB_SEGMERCADO.DESCRICAO%TYPE;
BEGIN
    v_DESCRICAO := obter_descricao_segmercado(2);
    DBMS_OUTPUT.put_line('A descrição do campo é: '||v_DESCRICAO);
END;

select count(*) 
from user_tab_columns
where table_name='TAB_SEGMERCADO';

SELECT * FROM TAB_CLIENTE;

CREATE OR REPLACE PROCEDURE INCLUIR_CLIENTE
(v_ID IN TAB_CLIENTE.ID%TYPE, v_RAZAO_SOCIAL IN TAB_CLIENTE.RAZAO_SOCIAL%TYPE,
v_CNPJ IN TAB_CLIENTE.CNPJ%TYPE, v_SEGMERCADO_ID IN TAB_CLIENTE.SEGMERCADO_ID%TYPE,
v_DATA_INCLUSAO IN TAB_CLIENTE.DATA_INCLUSAO%TYPE, v_FATURAMENTO_PREVISTO IN TAB_CLIENTE.FATURAMENTO_PREVISTO%TYPE)
IS 
    v_CATEGORIA TAB_CLIENTE.CATEGORIA%TYPE;
    p_CNPJ TAB_CLIENTE.CNPJ%TYPE := v_CNPJ;
BEGIN
    v_CATEGORIA := CATEGORIA_CLIENTE(v_FATURAMENTO_PREVISTO);
    FORMATA_CLIENTE(p_CNPJ);
    
    INSERT INTO TAB_CLIENTE (ID, RAZAO_SOCIAL, CNPJ, SEGMERCADO_ID, DATA_INCLUSAO, FATURAMENTO_PREVISTO, CATEGORIA)
    VALUES
    (v_ID, v_RAZAO_SOCIAL, p_CNPJ, v_SEGMERCADO_ID, v_DATA_INCLUSAO, v_FATURAMENTO_PREVISTO, v_CATEGORIA);
END;

EXECUTE INCLUIR_CLIENTE(1, 'Supermercado JK Iguatemi', '67800', 2, SYSDATE, 900000);

SELECT * FROM TAB_CLIENTE;

DELETE FROM TAB_CLIENTE;

CREATE OR REPLACE FUNCTION CATEGORIA_CLIENTE
(v_FATURAMENTO_PREVISTO IN TAB_CLIENTE.FATURAMENTO_PREVISTO%TYPE)
RETURN TAB_CLIENTE.CATEGORIA%TYPE
IS
    v_CATEGORIA TAB_CLIENTE.CATEGORIA%TYPE;
BEGIN
    IF v_FATURAMENTO_PREVISTO < 1000 THEN
    v_CATEGORIA := 'PEQUENO';
    ELSIF v_FATURAMENTO_PREVISTO < 10000 THEN
    v_CATEGORIA := 'MÉDIO';
    ELSIF v_FATURAMENTO_PREVISTO < 100000 THEN
    v_CATEGORIA := 'GRANDE';
    ELSE
    v_CATEGORIA := 'FATURAMENTO ACIMA DO PREVISTO';
    END IF;
    RETURN v_CATEGORIA;
    dbms_output.put_line(v_CATEGORIA);
END;

VARIABLE v_CAT VARCHAR2(100);

EXECUTE :v_CAT := CATEGORIA_CLIENTE(10000);

PRINT v_CAT;