-- FUNÇÃO IN OUT

CREATE OR REPLACE PROCEDURE FORMATA_CLIENTE
(p_CNPJ IN OUT TAB_CLIENTE.CNPJ%TYPE)
IS
BEGIN
    p_CNPJ := SUBSTR(p_CNPJ, 1, 2) || '/' || SUBSTR(p_CNPJ, 3, 2) || '-' || SUBSTR(p_CNPJ, 5, 1);
END;

VARIABLE p_CNPJ VARCHAR2(50);

EXEC :p_CNPJ := '12345';

EXEC FORMATA_CLIENTE(:p_CNPJ);

PRINT :p_CNPJ;

DESC TAB_CLIENTE;