DECLARE
    v_SEGMERCADO_ID TAB_CLIENTE.SEGMERCADO_ID%TYPE := 2;
    v_CONTADOR NUMBER(10) := 1;
BEGIN
    LOOP
        ATUALIZAR_ID(v_CONTADOR, v_SEGMERCADO_ID);
        v_CONTADOR := v_CONTADOR + 1;
        EXIT WHEN v_CONTADOR > 5;
    END LOOP;
END;

SELECT * FROM TAB_CLIENTE;

SELECT * FROM TAB_SEGMERCADO;
