CREATE OR REPLACE PROCEDURE INCLUIR_SEGMERCADO (p_ID IN TAB_SEGMERCADO.ID%TYPE, p_DESCRICAO IN TAB_SEGMERCADO.DESCRICAO%TYPE)
IS 
BEGIN INSERT INTO TAB_SEGMERCADO (ID, DESCRICAO) VALUES (p_ID, p_DESCRICAO);
COMMIT;
END;