-- DEFININDO A EXIBIÇÃO PELA SAÍDA DO SCRIPT
SET SERVEROUTPUT ON;

DECLARE
    v_ID NUMBER(5) := 5;
BEGIN
    v_ID := 1;
    dbms_output.put_line(v_ID);
END;

SELECT * FROM TAB_SEGMERCADO;
INSERT INTO TAB_SEGMERCADO(ID, DESCRICAO) VALUES (1, 'Varejo');
DELETE FROM TAB_SEGMERCADO;

DECLARE 
    v_ID NUMBER(5) := 5;
    v_DESCRICAO VARCHAR(100) := 'Varejo';
BEGIN
    INSERT INTO TAB_SEGMERCADO (ID, DESCRICAO) VALUES (v_ID, v_DESCRICAO);
    COMMIT;
END;