
DESC TAB_SEGMERCADO;

SELECT * FROM TAB_SEGMERCADO;

CREATE PROCEDURE INCLUIR_SEGMERCADO (p_ID IN NUMBER, p_DESCRICAO VARCHAR2)
IS 
BEGIN INSERT INTO TAB_SEGMERCADO (ID, DESCRICAO) VALUES (p_ID, p_DESCRICAO);
COMMIT;
END;

EXEC INCLUIR_SEGMERCADO(1, 'Farmaceutico');


