create or replace NONEDITIONABLE PROCEDURE INCLUIR_CLIENTE
(v_ID IN TAB_CLIENTE.ID%TYPE, v_RAZAO_SOCIAL IN TAB_CLIENTE.RAZAO_SOCIAL%TYPE,
v_CNPJ IN TAB_CLIENTE.CNPJ%TYPE, v_SEGMERCADO_ID IN TAB_CLIENTE.SEGMERCADO_ID%TYPE,
v_DATA_INCLUSAO IN TAB_CLIENTE.DATA_INCLUSAO%TYPE, v_FATURAMENTO_PREVISTO IN TAB_CLIENTE.FATURAMENTO_PREVISTO%TYPE)
IS 
    v_CATEGORIA TAB_CLIENTE.CATEGORIA%TYPE;
    p_CNPJ TAB_CLIENTE.CNPJ%TYPE := v_CNPJ;
    e_null exception;
    PRAGMA EXCEPTION_INIT (e_null, -1400);
BEGIN
    v_CATEGORIA := CATEGORIA_CLIENTE(v_FATURAMENTO_PREVISTO);
    FORMATA_CLIENTE(p_CNPJ);

    INSERT INTO TAB_CLIENTE (ID, RAZAO_SOCIAL, CNPJ, SEGMERCADO_ID, DATA_INCLUSAO, FATURAMENTO_PREVISTO, CATEGORIA)
    VALUES
    (v_ID, v_RAZAO_SOCIAL, p_CNPJ, v_SEGMERCADO_ID, v_DATA_INCLUSAO, v_FATURAMENTO_PREVISTO, v_CATEGORIA);
    
    -- dup_val_on_index = violação de constraints
    EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20012, 'Contacte o Administrador, problema não previsto | ' || sqlerrm());
    WHEN dup_val_on_index THEN
        RAISE_APPLICATION_ERROR(-20010, 'Cliente não pode ser cadastrado novamente');
    WHEN e_null THEN
        RAISE_APPLICATION_ERROR(-20011, 'Não é possível cadastrar ID com NULL');
    
END;