create or replace NONEDITIONABLE PROCEDURE ATUALIZAR_SEGMERCADO_ID
(v_ID TAB_CLIENTE.ID%TYPE, v_ATUALIZAR_SEGMERCADO_ID TAB_CLIENTE.SEGMERCADO_ID%TYPE)
IS
    e_CLIENTE EXCEPTION;
BEGIN
    UPDATE TAB_CLIENTE SET SEGMERCADO_ID = v_ATUALIZAR_SEGMERCADO_ID
    WHERE ID = v_ID;
    IF SQL%NOTFOUND THEN
        RAISE e_CLIENTE;
    END IF;
    COMMIT;
    EXCEPTION
        WHEN e_CLIENTE THEN
             RAISE_APPLICATION_ERROR(-20020, 'CLIENTE INEXISTENTE!');
END;